# Generated by Django 2.2.5 on 2019-10-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movielist',
            unique_together=set(),
        ),
    ]
