# Generated by Django 2.2.5 on 2019-10-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191003_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
