# Generated by Django 2.2.5 on 2019-10-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movielistitem_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielistitem',
            name='movie_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.MovieList'),
        ),
    ]
