# Generated by Django 2.2.5 on 2019-10-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191008_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielistitem',
            name='plot',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
