# Generated by Django 2.2.5 on 2019-10-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movielistitem_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='slug',
            new_name='slug_list',
        ),
        migrations.AddField(
            model_name='movielistitem',
            name='slug_item',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
