# Generated by Django 2.2.5 on 2019-10-09 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20191009_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielistitem',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
