# Generated by Django 2.2.5 on 2019-10-10 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20191010_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
