# Generated by Django 2.2.5 on 2019-10-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20191010_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielistitem',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
