# Generated by Django 2.2.5 on 2019-10-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movielistitem_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielistitem',
            name='rating',
        ),
    ]
