# Generated by Django 2.2.5 on 2019-10-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_movielistitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielistitem',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
