# Generated by Django 2.2.5 on 2019-10-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movielistitem_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielistitem',
            name='rating',
        ),
        migrations.AlterField(
            model_name='movielistitem',
            name='plot',
            field=models.CharField(max_length=300),
        ),
    ]
