# Generated by Django 2.2.5 on 2019-10-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20191010_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='movie_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.MovieList'),
        ),
    ]
