# Generated by Django 2.2.5 on 2019-10-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20191011_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movierating',
            old_name='movie_list',
            new_name='movie',
        ),
    ]
