# Generated by Django 2.2.5 on 2019-10-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20191011_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielistitem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
