# Generated by Django 2.2.5 on 2019-10-11 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0022_auto_20191011_1149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movierating',
            unique_together={('user', 'movie')},
        ),
    ]
