# Generated by Django 2.2.5 on 2019-10-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_auto_20191011_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielistitem',
            name='slug',
        ),
    ]
