# Generated by Django 2.2.5 on 2019-10-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_auto_20191011_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
